[build]
  command = "cd client && npm install && npm run build"
  publish = "client/dist"
  functions = "server/netlify/functions"

[functions]
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 8888