[build]
  base = "client"
  command = "npm run build"
  publish = "dist"

# Express backend
[functions]
  directory = "server/netlify/functions/dist"

# API-omdirigeringar för Express-app
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api"
status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200